# Generated by Django 3.1.2 on 2020-10-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='tack',
            new_name='track',
        ),
    ]
